services:
  database:
    image: postgres:18
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hatohui
    ports:
      - '5437:5432'
    volumes:
      - db_data:/var/lib/postgresql

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: root
    command: server /data
    ports:
      - '9000:9000'
    volumes:
      - minio_data:/data

  mailpit:
    image: axllent/mailpit
    ports:
      - '8025:8025'
      - '1025:1025'

  redis:
    image: redis:8-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  db_data:
  minio_data:
  redis_data:
