name: art-cd

on:
  push:
    branches: [master]
    paths:
      - "apps/art/**"
      - "packages/**"
      - ".github/workflows/art-cd.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: hatohui/publish-cloudflare-pages@v2
        with:
          target: worker
          package: apps/art/package.json
          build_script: cf:build
          deploy_script: cf:deploy
          cloudflare_account_id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          build_environments: |
            NEXT_PUBLIC_API_URL=${{ vars.API_URL }}
            NEXT_PUBLIC_ASSET_URL=${{ vars.ASSET_URL }}
            NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_ID=${{ vars.GOOGLE_OAUTH_CLIENT_ID }}
