name: friends-cd

on:
  push:
    branches: [master]
    paths:
      - "apps/friends/**"
      - "packages/**"
      - ".github/workflows/friends-cd.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Deploy Friends
        uses: hatohui/publish-cloudflare-pages@v2
        with:
          dist: apps/friends/dist
          package: apps/friends/package.json
          project_name: friends
          cloudflare_account_id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          build_environments: |
            VITE_API_URL=${{ vars.API_URL }}
            VITE_GOOGLE_OAUTH_CLIENT_ID=${{ vars.GOOGLE_OAUTH_CLIENT_ID }}
