name: infra-cd

on:
  push:
    branches: [master]
    paths:
      - "infra/**"
      - ".github/workflows/infra-cd.yml"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Terraform apply
        uses: hatohui/doppler-terraform-apply@v0
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          doppler-project: hatohui-workspace
          doppler-config: tf
          working-directory: infra
          terraform-version: 1.15.8
          tf-api-token: ${{ secrets.TF_API_TOKEN }}
