name: workspace-cd

on:
  push:
    branches: [master]
    paths:
      - "apps/workspace/**"
      - "packages/**"
      - ".github/workflows/workspace-cd.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Deploy Workspace
        uses: hatohui/publish-cloudflare-pages@v2.2.0
        with:
          dist: apps/workspace/dist
          package: apps/workspace/package.json
          project_name: workspace
          cloudflare_account_id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          build_environments: |
            VITE_API_URL=${{ vars.API_URL }}
            VITE_GOOGLE_OAUTH_CLIENT_ID=${{ vars.GOOGLE_OAUTH_CLIENT_ID }}
